/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pbo.proyekakhirpbo.ui;
import com.pbo.proyekakhirpbo.db.Konektor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class DialogTransaksi extends javax.swing.JDialog {
    private String idTransaksi;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogTransaksi.class.getName());

    /**
     * Creates new form DialogTransaksi
     */
    public DialogTransaksi(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        this.idTransaksi = id; // Save the ID
        initComponents();
        this.setSize(500, 500); // Adjust size if needed
        
        // Show ID in title or label
        detailTransaksi.setText("DETAIL TRANSAKSI ID: " + id);
        
        // Load the data immediately
        loadDetail();
    }
    private void loadDetail() {
        DefaultTableModel model = (DefaultTableModel) tebalTDetail.getModel();
        model.setRowCount(0); // Clear table

        try {
            Connection conn = Konektor.getConnection();
            // Join detail_transaksi with produk to get product names
            String sql = "SELECT p.nama_barang, d.harga, d.kuantitas, (d.harga * d.kuantitas) as subtotal " +
                         "FROM detail_transaksi d " +
                         "JOIN produk p ON d.id_produk = p.id_produk " +
                         "WHERE d.id_transaksi = ?";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idTransaksi);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String nama = rs.getString("nama_barang");
                String harga = String.valueOf((long)rs.getDouble("harga"));
                String qty = String.valueOf(rs.getInt("kuantitas"));
                String sub = String.valueOf((long)rs.getDouble("subtotal"));

                model.addRow(new Object[]{ nama, harga, qty, sub });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat detail: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransaksi = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        detailTransaksi = new javax.swing.JLabel();
        ubahKeLunas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tebalTDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        panelTransaksi.setPreferredSize(new java.awt.Dimension(426, 365));

        jPanel2.setBackground(new java.awt.Color(0, 32, 64));

        detailTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        detailTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        detailTransaksi.setText("DETAIL TRANSAKSI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(detailTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ubahKeLunas.setText("Ubah ke Lunas");
        ubahKeLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahKeLunasActionPerformed(evt);
            }
        });

        tebalTDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Produk", "Harga", "Qty", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tebalTDetail);

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaksiLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaksiLayout.createSequentialGroup()
                        .addComponent(ubahKeLunas)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaksiLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(ubahKeLunas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubahKeLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahKeLunasActionPerformed
        int jawab = JOptionPane.showConfirmDialog(this, 
                "Ubah status transaksi ID " + idTransaksi + " menjadi LUNAS?", 
                "Konfirmasi", 
                JOptionPane.YES_NO_OPTION);
    
        if (jawab == JOptionPane.YES_OPTION) {
            try {
                Connection conn = Konektor.getConnection();
                String sql = "UPDATE transaksi SET status = 'Lunas' WHERE id_transaksi = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, idTransaksi);
                
                int rows = pst.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Status Berhasil Diupdate!");
                    this.dispose(); // Close dialog
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error update: " + e.getMessage());
            }
        }
    
    }//GEN-LAST:event_ubahKeLunasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogTransaksi dialog = new DialogTransaksi(new javax.swing.JFrame(), true, "Contoh");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailTransaksi;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JTable tebalTDetail;
    private javax.swing.JButton ubahKeLunas;
    // End of variables declaration//GEN-END:variables
}
