/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbo.proyekakhirpbo.ui;

/**
 *
 * @author Asus
 */
public class FrameAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameAdmin.class.getName());

    /**
     * Creates new form FrameAdmin
     */
    public FrameAdmin() {
        initComponents();
        panelKosong.setLayout(new java.awt.BorderLayout());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new javax.swing.JPanel();
        AdminPanel = new javax.swing.JLabel();
        dashboardClick = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        barangClick = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        transaksiClick = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logoutClick = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelKosong = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(735, 565));

        panelAdmin.setBackground(new java.awt.Color(0, 32, 64));
        panelAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAdmin.setPreferredSize(new java.awt.Dimension(200, 565));

        AdminPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AdminPanel.setForeground(new java.awt.Color(255, 255, 255));
        AdminPanel.setText("Admin Panel");

        dashboardClick.setBackground(new java.awt.Color(0, 32, 64));
        dashboardClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardClickMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout dashboardClickLayout = new javax.swing.GroupLayout(dashboardClick);
        dashboardClick.setLayout(dashboardClickLayout);
        dashboardClickLayout.setHorizontalGroup(
            dashboardClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardClickLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardClickLayout.setVerticalGroup(
            dashboardClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardClickLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        barangClick.setBackground(new java.awt.Color(0, 32, 64));
        barangClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangClickMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kelola Barang");

        javax.swing.GroupLayout barangClickLayout = new javax.swing.GroupLayout(barangClick);
        barangClick.setLayout(barangClickLayout);
        barangClickLayout.setHorizontalGroup(
            barangClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangClickLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barangClickLayout.setVerticalGroup(
            barangClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barangClickLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        transaksiClick.setBackground(new java.awt.Color(0, 32, 64));
        transaksiClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiClickMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kelola Transaksi");

        javax.swing.GroupLayout transaksiClickLayout = new javax.swing.GroupLayout(transaksiClick);
        transaksiClick.setLayout(transaksiClickLayout);
        transaksiClickLayout.setHorizontalGroup(
            transaksiClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiClickLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksiClickLayout.setVerticalGroup(
            transaksiClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiClickLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        logoutClick.setBackground(new java.awt.Color(0, 32, 64));
        logoutClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutClickMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Logout");

        javax.swing.GroupLayout logoutClickLayout = new javax.swing.GroupLayout(logoutClick);
        logoutClick.setLayout(logoutClickLayout);
        logoutClickLayout.setHorizontalGroup(
            logoutClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutClickLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoutClickLayout.setVerticalGroup(
            logoutClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutClickLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AdminPanel)
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(dashboardClick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barangClick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaksiClick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutClick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AdminPanel)
                .addGap(85, 85, 85)
                .addComponent(dashboardClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barangClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transaksiClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        getContentPane().add(panelAdmin, java.awt.BorderLayout.WEST);

        panelKosong.setBackground(new java.awt.Color(255, 255, 255));
        panelKosong.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Welcome, Admin!");
        panelKosong.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panelKosong, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Method untuk ganti konten di panelKosong
private void gantiHalaman(javax.swing.JPanel halamanBaru) {
    //  Bersihkan panelKosong dari konten sebelumnya
    panelKosong.removeAll(); 

    panelKosong.add(halamanBaru);

    panelKosong.revalidate();
    panelKosong.repaint();
}

    private void dashboardClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardClickMouseClicked
        gantiHalaman(new PanelDashboard());
    }//GEN-LAST:event_dashboardClickMouseClicked

    private void barangClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangClickMouseClicked
        gantiHalaman(new PanelBarang());
    }//GEN-LAST:event_barangClickMouseClicked

    private void transaksiClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiClickMouseClicked
        gantiHalaman(new PanelTransaksi());
    }//GEN-LAST:event_transaksiClickMouseClicked

    private void logoutClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutClickMouseClicked
        this.dispose(); 

        new FrameSignUp().setVisible(true);
    }//GEN-LAST:event_logoutClickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminPanel;
    private javax.swing.JPanel barangClick;
    private javax.swing.JPanel dashboardClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel logoutClick;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelKosong;
    private javax.swing.JPanel transaksiClick;
    // End of variables declaration//GEN-END:variables
}
