/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.proyekakhirpbo.ui;

import com.pbo.proyekakhirpbo.ui.DialogTransaksi;
import com.pbo.proyekakhirpbo.db.Konektor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class PanelTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form PanelTransaksi
     */
    public PanelTransaksi() {
        initComponents();
        tabelTransaksi.setDefaultEditor(Object.class, null);
        loadData();
    }
    
    private void loadData() {
    DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        
        // 1. CLEAR DUMMY DATA
        model.setRowCount(0); 

        try {
            Connection conn = Konektor.getConnection();
            
            // 2. QUERY DATABASE
            // We join 'transaksi' with 'user' to get the name (e.g. "Aulia R") instead of just ID "5"
            String sql = "SELECT t.id_transaksi, u.nama, t.created_at, t.total, t.status " +
                         "FROM transaksi t " +
                         "JOIN user u ON t.id_user = u.id_user " +
                         "ORDER BY t.created_at DESC";
                         
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id_transaksi"));
                String user = rs.getString("nama");
                String tgl = rs.getString("created_at"); // Matches your DB column 'created_at'
                String total = String.valueOf((long)rs.getDouble("total"));
                String status = rs.getString("status");

                // Add to table
                model.addRow(new Object[]{ id, user, tgl, total, status, "Detail" });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat transaksi: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransaksi = new javax.swing.JPanel();
        kelolaTransaksiBarang = new javax.swing.JLabel();
        cariBarangField = new javax.swing.JTextField();
        hapusTransaksiButton = new javax.swing.JButton();
        cariBarangButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        panelTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        panelTransaksi.setPreferredSize(new java.awt.Dimension(535, 565));

        kelolaTransaksiBarang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        kelolaTransaksiBarang.setForeground(new java.awt.Color(0, 32, 64));
        kelolaTransaksiBarang.setText("Kelola Transaksi Barang");

        hapusTransaksiButton.setBackground(new java.awt.Color(0, 32, 64));
        hapusTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusTransaksiButton.setText("Hapus");
        hapusTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTransaksiButtonActionPerformed(evt);
            }
        });

        cariBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        cariBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        cariBarangButton.setText("Cari");
        cariBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBarangButtonActionPerformed(evt);
            }
        });

        tabelTransaksi.setBackground(new java.awt.Color(204, 204, 204));
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID. Transaksi", "User", "Tanggal", "Total", "Status", "Aksi"
            }
        ));
        tabelTransaksi.setRowHeight(30);
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel1.setText("240002 - 240036 - 240060");

        jLabel2.setText("Cari ID Transaksi");

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransaksiLayout.createSequentialGroup()
                        .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransaksiLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(hapusTransaksiButton))
                            .addComponent(kelolaTransaksiBarang))
                        .addGap(18, 18, 18)
                        .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cariBarangField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariBarangButton)))
                .addGap(12, 12, 12))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(kelolaTransaksiBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)))
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusTransaksiButton)
                    .addComponent(cariBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBarangButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        if (evt.getClickCount() == 2) {
            
            int baris = tabelTransaksi.getSelectedRow();

            if (baris >= 0) {
                String idSelected = tabelTransaksi.getValueAt(baris, 0).toString(); 

                DialogTransaksi dialog = new DialogTransaksi(new javax.swing.JFrame(), true, idSelected);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                
                // Refresh table after dialog closes (in case status changed to Lunas)
                loadData();
            }
        }
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void hapusTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTransaksiButtonActionPerformed
        int selectedRow = tabelTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dihapus!");
            return;
        }

        // 2. Get the ID (Column 0 is ID Transaksi)
        String idTrans = tabelTransaksi.getValueAt(selectedRow, 0).toString();

        // 3. Confirm Deletion
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Hapus riwayat transaksi ID: " + idTrans + "?\nData tidak bisa dikembalikan.", 
                "Konfirmasi Hapus", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = com.pbo.proyekakhirpbo.db.Konektor.getConnection();
                
                // --- STEP A: Delete the Details first (Safety Step) ---
                // Even if you have CASCADE on, doing this explicitly is safer in Java code
                String sqlDetail = "DELETE FROM detail_transaksi WHERE id_transaksi = ?";
                java.sql.PreparedStatement pstDetail = conn.prepareStatement(sqlDetail);
                pstDetail.setInt(1, Integer.parseInt(idTrans));
                pstDetail.executeUpdate();

                // --- STEP B: Delete the Header ---
                String sql = "DELETE FROM transaksi WHERE id_transaksi = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(idTrans));
                pst.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Data Transaksi Berhasil Dihapus");
                
                // 4. Refresh the Table
                loadData(); 
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_hapusTransaksiButtonActionPerformed

    private void cariBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBarangButtonActionPerformed
        String keyword = cariBarangField.getText();
        
        // 2. Clear the table before showing results
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelTransaksi.getModel();
        model.setRowCount(0);

        try {
            java.sql.Connection conn = com.pbo.proyekakhirpbo.db.Konektor.getConnection();
            
            // 3. Search Query
            // We search in 'transaksi.id_transaksi' OR 'user.nama'
            String sql = "SELECT t.id_transaksi, u.nama, t.created_at, t.total, t.status " +
                         "FROM transaksi t " +
                         "JOIN user u ON t.id_user = u.id_user " +
                         "WHERE t.id_transaksi LIKE ? OR u.nama LIKE ? " +
                         "ORDER BY t.created_at DESC";
            
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%"); // % allows partial match
            pst.setString(2, "%" + keyword + "%");
            
            java.sql.ResultSet rs = pst.executeQuery();

            // 4. Loop through results and add to table
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id_transaksi"));
                String user = rs.getString("nama");
                String tgl = rs.getString("created_at"); 
                // Format price to remove decimals (e.g. 50000.00 -> 50000)
                String total = String.valueOf((long)rs.getDouble("total")); 
                String status = rs.getString("status");

                model.addRow(new Object[]{ id, user, tgl, total, status, "Detail" });
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pencarian Gagal: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariBarangButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBarangButton;
    private javax.swing.JTextField cariBarangField;
    private javax.swing.JButton hapusTransaksiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelolaTransaksiBarang;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
