/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.proyekakhirpbo.ui;

import com.pbo.proyekakhirpbo.ui.DialogTambahBarang;

/**
 *
 * @author Asus
 */
public class PanelBarang extends javax.swing.JPanel {

    /**
     * Creates new form PanelBarang
     */
    public PanelBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kelolaDataBarang = new javax.swing.JLabel();
        cariBarangField = new javax.swing.JTextField();
        tambahBarangButton = new javax.swing.JButton();
        editBarangButton = new javax.swing.JButton();
        hapusBarangButton = new javax.swing.JButton();
        cariBarangButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarangButton = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(535, 565));

        kelolaDataBarang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        kelolaDataBarang.setForeground(new java.awt.Color(0, 32, 64));
        kelolaDataBarang.setText("Kelola Data Barang");

        cariBarangField.setText("Cari...");

        tambahBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        tambahBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahBarangButton.setText("Tambah");
        tambahBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangButtonActionPerformed(evt);
            }
        });

        editBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        editBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        editBarangButton.setText("Edit");

        hapusBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        hapusBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusBarangButton.setText("Hapus");

        cariBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        cariBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        cariBarangButton.setText("Cari");

        tabelBarangButton.setBackground(new java.awt.Color(204, 204, 204));
        tabelBarangButton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID. Barang", "Gambar", "Nama Barang", "Stok", "Harga", "Aksi"
            }
        ));
        tabelBarangButton.setRowHeight(30);
        jScrollPane1.setViewportView(tabelBarangButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kelolaDataBarang)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tambahBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(editBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(hapusBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(cariBarangField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cariBarangButton)))
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(kelolaDataBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBarangButton)
                    .addComponent(editBarangButton)
                    .addComponent(hapusBarangButton)
                    .addComponent(cariBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBarangButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangButtonActionPerformed
        DialogTambahBarang dialog = new DialogTambahBarang(new javax.swing.JFrame(), true);
    
        // 2. Mengatur posisi agar muncul di tengah layar
        dialog.setLocationRelativeTo(null);

        // 3. Menampilkan dialog
        dialog.setVisible(true);
    }//GEN-LAST:event_tambahBarangButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBarangButton;
    private javax.swing.JTextField cariBarangField;
    private javax.swing.JButton editBarangButton;
    private javax.swing.JButton hapusBarangButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelolaDataBarang;
    private javax.swing.JTable tabelBarangButton;
    private javax.swing.JButton tambahBarangButton;
    // End of variables declaration//GEN-END:variables
}
