/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.proyekakhirpbo.ui;

import com.pbo.proyekakhirpbo.ui.DialogTambahBarang;
import com.pbo.proyekakhirpbo.db.Konektor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class PanelBarang extends javax.swing.JPanel {

    /**
     * Creates new form PanelBarang
     */
    public PanelBarang() {
        initComponents();
        loadTable();
    }
    
    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) tabelBarangButton.getModel();
        model.setRowCount(0);

        try {
            Connection conn = Konektor.getConnection();
            Statement stmt = conn.createStatement();
            String sql = "SELECT * FROM produk";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id_produk"));
                String nama = rs.getString("nama_barang");
                String deskripsi = rs.getString("deskripsi"); 
                String stok = String.valueOf(rs.getInt("stok_barang"));
                String harga = String.valueOf(rs.getDouble("harga_barang"));
                
                String gambarInfo = (rs.getBytes("image_barang") != null) ? "Ada Gambar" : "Tidak Ada";

                model.addRow(new Object[]{id, gambarInfo, nama, deskripsi, stok, harga});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kelolaDataBarang = new javax.swing.JLabel();
        cariBarangField = new javax.swing.JTextField();
        tambahBarangButton = new javax.swing.JButton();
        editBarangButton = new javax.swing.JButton();
        hapusBarangButton = new javax.swing.JButton();
        cariBarangButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarangButton = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(535, 565));

        kelolaDataBarang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        kelolaDataBarang.setForeground(new java.awt.Color(0, 32, 64));
        kelolaDataBarang.setText("Kelola Data Barang");

        tambahBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        tambahBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahBarangButton.setText("Tambah");
        tambahBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangButtonActionPerformed(evt);
            }
        });

        editBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        editBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        editBarangButton.setText("Edit");
        editBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBarangButtonActionPerformed(evt);
            }
        });

        hapusBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        hapusBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusBarangButton.setText("Hapus");
        hapusBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBarangButtonActionPerformed(evt);
            }
        });

        cariBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        cariBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        cariBarangButton.setText("Cari");
        cariBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBarangButtonActionPerformed(evt);
            }
        });

        tabelBarangButton.setBackground(new java.awt.Color(204, 204, 204));
        tabelBarangButton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID. Barang", "Gambar", "Nama Barang", "Deskripsi", "Stok", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBarangButton.setRowHeight(30);
        jScrollPane1.setViewportView(tabelBarangButton);

        jLabel1.setText("240002 - 240036 - 240060");

        jLabel2.setText("Cari nama barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tambahBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(editBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(hapusBarangButton))
                            .addComponent(kelolaDataBarang))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cariBarangField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariBarangButton)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kelolaDataBarang)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBarangButton)
                    .addComponent(editBarangButton)
                    .addComponent(hapusBarangButton)
                    .addComponent(cariBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBarangButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangButtonActionPerformed
        DialogTambahBarang dialog = new DialogTambahBarang(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null); 
        dialog.setVisible(true); 
        
        loadTable();
    }//GEN-LAST:event_tambahBarangButtonActionPerformed

    private void editBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBarangButtonActionPerformed
        int selectedRow = tabelBarangButton.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit!");
            return;
        }

        String id = tabelBarangButton.getValueAt(selectedRow, 0).toString();
        String nama = tabelBarangButton.getValueAt(selectedRow, 2).toString();
        String deskripsi = tabelBarangButton.getValueAt(selectedRow, 3).toString(); 
        String stok = tabelBarangButton.getValueAt(selectedRow, 4).toString();
        String harga = tabelBarangButton.getValueAt(selectedRow, 5).toString();

        DialogTambahBarang dialog = new DialogTambahBarang(new javax.swing.JFrame(), true);
        
        dialog.setEditData(id, nama, stok, harga, deskripsi); 
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
        loadTable();
    }//GEN-LAST:event_editBarangButtonActionPerformed

    private void hapusBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBarangButtonActionPerformed
        int selectedRow = tabelBarangButton.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus terlebih dahulu!");
            return;
        }

        String idProduk = tabelBarangButton.getValueAt(selectedRow, 0).toString();

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Apakah anda yakin ingin menghapus produk ID: " + idProduk + "?", 
                "Konfirmasi Hapus", 
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = com.pbo.proyekakhirpbo.db.Konektor.getConnection();
                String sql = "DELETE FROM produk WHERE id_produk = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, Integer.parseInt(idProduk));
                
                pst.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                
                loadTable();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_hapusBarangButtonActionPerformed

    private void cariBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBarangButtonActionPerformed
       String keyword = cariBarangField.getText();
        DefaultTableModel model = (DefaultTableModel) tabelBarangButton.getModel();
        model.setRowCount(0);

        try {
            Connection conn = Konektor.getConnection();
            String sql = "SELECT * FROM produk WHERE nama_barang LIKE '%" + keyword + "%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id_produk"));
                String nama = rs.getString("nama_barang");
                String deskripsi = rs.getString("deskripsi");
                String stok = String.valueOf(rs.getInt("stok_barang"));
                String harga = String.valueOf(rs.getDouble("harga_barang"));
                String gambarInfo = (rs.getBytes("image_barang") != null) ? "Ada" : "Tidak";

                model.addRow(new Object[]{id, gambarInfo, nama, deskripsi, stok, harga});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariBarangButtonActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBarangButton;
    private javax.swing.JTextField cariBarangField;
    private javax.swing.JButton editBarangButton;
    private javax.swing.JButton hapusBarangButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelolaDataBarang;
    private javax.swing.JTable tabelBarangButton;
    private javax.swing.JButton tambahBarangButton;
    // End of variables declaration//GEN-END:variables
}
