/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.proyekakhirpbo.ui;

import com.pbo.proyekakhirpbo.ui.DialogTransaksi;

/**
 *
 * @author Asus
 */
public class PanelTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form PanelTransaksi
     */
    public PanelTransaksi() {
        initComponents();
        
        loadData();
    }
    
    private void loadData() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelTransaksi.getModel();
    
    // Bersihkan data lama 
    model.setRowCount(0);
    
    // Data Dummy (Nanti ini diganti sama loop Database)
    model.addRow(new Object[]{ "T001", "Aulia R", "04-12-2025", "150.000", "Lunas", " Detail" });
    model.addRow(new Object[]{ "T002", "Azhaar F", "05-12-2025", "75.000", "Pending", " Detail" });
    model.addRow(new Object[]{ "T003", "Joan C", "06-12-2025", "200.000", "Lunas", " Detail" });

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransaksi = new javax.swing.JPanel();
        kelolaTransaksiBarang = new javax.swing.JLabel();
        cariBarangField = new javax.swing.JTextField();
        tambahBarangButton = new javax.swing.JButton();
        editBarangButton = new javax.swing.JButton();
        hapusBarangButton = new javax.swing.JButton();
        cariBarangButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        panelTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        panelTransaksi.setPreferredSize(new java.awt.Dimension(535, 565));

        kelolaTransaksiBarang.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        kelolaTransaksiBarang.setForeground(new java.awt.Color(0, 32, 64));
        kelolaTransaksiBarang.setText("Kelola Transaksi Barang");

        tambahBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        tambahBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahBarangButton.setText("Tambah");

        editBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        editBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        editBarangButton.setText("Edit");

        hapusBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        hapusBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusBarangButton.setText("Hapus");

        cariBarangButton.setBackground(new java.awt.Color(0, 32, 64));
        cariBarangButton.setForeground(new java.awt.Color(255, 255, 255));
        cariBarangButton.setText("Cari");

        tabelTransaksi.setBackground(new java.awt.Color(204, 204, 204));
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID. Transaksi", "User", "Tanggal", "Total", "Status", "Aksi"
            }
        ));
        tabelTransaksi.setRowHeight(30);
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel1.setText("240002 - 240036 - 240060");

        jLabel2.setText("Cari ID Transaksi");

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransaksiLayout.createSequentialGroup()
                        .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransaksiLayout.createSequentialGroup()
                                .addComponent(tambahBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(editBarangButton)
                                .addGap(18, 18, 18)
                                .addComponent(hapusBarangButton))
                            .addComponent(kelolaTransaksiBarang))
                        .addGap(18, 18, 18)
                        .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cariBarangField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariBarangButton)))
                .addGap(12, 12, 12))
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransaksiLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(kelolaTransaksiBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)))
                .addGroup(panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBarangButton)
                    .addComponent(editBarangButton)
                    .addComponent(hapusBarangButton)
                    .addComponent(cariBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBarangButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        int baris = tabelTransaksi.getSelectedRow();

    if (baris >= 0) {

        DialogTransaksi dialog = new DialogTransaksi(new javax.swing.JFrame(), true, "T001");
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    }//GEN-LAST:event_tabelTransaksiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariBarangButton;
    private javax.swing.JTextField cariBarangField;
    private javax.swing.JButton editBarangButton;
    private javax.swing.JButton hapusBarangButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelolaTransaksiBarang;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tambahBarangButton;
    // End of variables declaration//GEN-END:variables
}
